### ISSUE TITLE
React Hot Loader

### ISSUE THREAD

**Issue by matias-casal** [srinisoundar/react-webpack-babel-kit#1]
Hi, i got this error:

Module build failed: Error: React Hot Loader: The Webpack loader is now exported separately. If you use Babel, we recommend that you remove "react-hot-loader" from the "loaders" section of your Webpack configuration altogether, and instead add "react-hot-loader/babel" to the "plugins" section of your .babelrc file. If you prefer not to use Babel, replace "react-hot-loader" or "react-hot" with "react-hot-loader/webpack" in the "loaders" section of your Webpack configuration.

**Comment by maxifjaved** [comment]
Its simple to fix man:

**.babelrc** looks like

`{
  "presets":["es2015", "react"],
  "plugins": ["react-hot-loader/babel"]
}
`

and  **webpack.config.dev.js** is like

 `
import path from 'path';
import webpack from 'webpack';
export default{
  devtools:'eval-source-map',
  entry: [
    path.join(__dirname, '/client/app.js'),
  ],
  output:{
    path: '/',
    publicPath: '/'
  },
  plugins:[
    new webpack.NoErrorsPlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin()
  ],
  module:{
    loaders:[
      {
        test: /\.js$/,
        include: path.join(__dirname, 'client'),
        loaders: ['babel' ]
      }
    ]
  },
  resolve:{
    extentions:['','.js']
  }
}
`

**Comment by xiaoxiangdaiyu** [comment]
@maxifjaved  hi maxifjaved .
i do that you say，but get this error:ReferenceError: Unknown plugin "react-hot-loader/babel".    i installed react-hot-loader with version 3.0.0-beta.6.

**Comment by maxifjaved** [comment]
try it after downgrade the webpack version

**Comment by xiaoxiangdaiyu** [comment]
i may do other thing wrong.  this is other error :  The plugin "react-hot-loader/babel" didn't export a Plugin instance

**Comment by xiaoxiangdaiyu** [comment]
@maxifjaved  i find what is going wrong. i do not update babel version.
thanks very much!

**Comment by srinisoundar** [comment]
Hi guys sorry for the delayed reply, I will update the kit.

**Comment by srinisoundar** [comment]
fixed. the kit is updated with latest versions.

**Comment by maxifjaved** [comment]
just created a stater kit : https://github.com/maxifjaved/react-webpack-express-boilerplate
you can start.
