### ISSUE TITLE
Module not found: Error: Can't resolve 'style-loader'

### ISSUE THREAD

**Issue by martinchristov** [srinisoundar/react-webpack-babel-kit#3]
Looks like an awesome setup, but following the instructions in readme.md leads to the error:

    ERROR in ./src/scripts/main.js
    Module not found: Error: Can't resolve 'style-loader' in '/Users/martin/play/react-webpack-babel-kit/src'
     @ ./src/scripts/main.js 6:0-31

**Comment by srinisoundar** [comment]
Hi,

I see style-loader is missing in the package.json I updated the dependencies, you can take a pull or you can solve it by running the below command on the root folder. Thanks for raising an issue.

npm install -D style-loader 

Regards,
Srini

**Comment by martinchristov** [comment]
Hi Srini,
I cloned the latest repo and I also tried what you suggested, but I am still getting the same error :/

**Comment by srinisoundar** [comment]
Hi Martin,

Did you try **npm install -D style-loader** in the command??

Regards,
Srini

**Comment by martinchristov** [comment]
Indeed I did. 

Perhaps you can try to get a fresh copy of the repo and try to run npm install & npm start

**Comment by srinisoundar** [comment]
weird. Can you share the complete logs ? Do you have any private npm package manager setup in your machine ?

**Comment by martinchristov** [comment]
https://www.dropbox.com/s/ejv3o1ka7u8wckb/Screenshot%202017-08-01%2008.59.14.png?dl=0

**Comment by srinisoundar** [comment]
Martin Thanks, sass-loader was missing. it has been added.

Changes has been pushed.

Regards,
Srini

**Comment by martinchristov** [comment]
Confirmed. Running "npm install -D sass-loader" is a fix.
Weird. I thought I had tried installing it previously. anywayz. thanks :)
